### ISSUE TITLE
Phone Number Update Bug

### ISSUE THREAD

**Issue by YasserShkeir** [abdallahmoubarak/water-monster-v2#2]
**Description**
"Phone Number Updated" Banner is displayed when focusing on the Phone Number Textarea and then unfocusing, even when no edits are made.

**To Reproduce**
1. Go to 'app/components/pages/secoundary/profile.tsx'
2. Line 55 contains updatePhone mutation, this will take us to app\hooks\useUser.ts
3. Line 46, requires a condition.

**Expected behavior**
Banner displayed only when phone is updated.

**Comment by abdallahmoubarak** [comment]
Hi Yasser, can you please send a screen record on slack.

**Comment by YasserShkeir** [comment]
Couldn't Repro - Issue Closed
